name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6.0.2

    - name: Build project
      run: make
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v7.0.1
      with:
        name: Stage 1 build
        path: build/
        retention-days: 14
